=== erikc5000/Confabulation-IRC/Confabulation/Files/Servers.dtd
<!ELEMENT Servers (Network*)>
<!ELEMENT Network (Server+)>
<!ELEMENT Server (Password?,Location?,Provider?,Details?)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Location (City?,State?,Country?,Region?)>
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Country (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT Provider (#PCDATA)>
<!ELEMENT Details (#PCDATA)>
<!ATTLIST Network Name CDATA #REQUIRED>
<!ATTLIST Server Index CDATA #REQUIRED>
<!ATTLIST Server Hostname CDATA #REQUIRED>
<!ATTLIST Server Ports CDATA "6667">
<!ATTLIST Location Random (True|False) "False">

=== erikc5000/Confabulation-IRC/Confabulation/Files/Servers.xml
<?xml version="1.0"?>
<!DOCTYPE Servers SYSTEM "Servers.dtd">
<Servers>
  <Network Name="GameSurge">
    <Server Index="0" Hostname="Co-Locate.NL.EU.GameSurge.net" Ports="6660-6669">
      <Location>
        <City>Amsterdam</City>
        <Country>NL</Country>
        <Region>EU</Region>
      </Location>
      <Provider>Co-Locate Internet BV</Provider>
    </Server>
    <Server Index="1" Hostname="GameServers.NJ.US.GameSurge.net" Ports="6665-6669,7000,8080">
      <Location>
        <City>Newark</City>
        <State>NJ</State>
        <Country>US</Country>
      </Location>
      <Provider>GameServers</Provider>
    </Server>
    <Server Index="2" Hostname="Gigenet.IL.US.GameSurge.net" Ports="6667-6669">
      <Location>
        <City>Chicago</City>
        <State>IL</State>
        <Country>US</Country>
      </Location>
      <Provider>GigEnet Servers</Provider>
    </Server>
    <Server Index="3" Hostname="Krypt.CA.US.GameSurge.net" Ports="6666-6669">
      <Location>
        <City>Santa Ana</City>
        <State>CA</State>
        <Country>US</Country>
      </Location>
      <Provider>Krypt</Provider>
    </Server>
    <Server Index="4" Hostname="NuclearFallout.WA.US.GameSurge.net" Ports="6667,5960">
      <Location>
        <City>Seattle</City>
        <State>WA</State>
        <Country>US</Country>
      </Location>
      <Provider>NuclearFallout</Provider>
    </Server>
    <Server Index="5" Hostname="Prothid.CA.US.GameSurge.Net" Ports="6667,5960">
      <Location>
        <City>Los Angeles</City>
        <State>CA</State>
        <Country>US</Country>
      </Location>
    </Server>
    <Server Index="6" Hostname="Burstfire.UK.EU.GameSurge.net" Ports="6667,6668,7000">
      <Location>
        <City>London</City>
        <Country>UK</Country>
        <Region>EU</Region>
      </Location>
      <Provider>Burstfire</Provider>
    </Server>
    <Server Index="7" Hostname="Clan-Server.AT.EU.GameSurge.net" Ports="6667-6669,7000">
      <Location>
        <City>Vienna</City>
        <Country>AT</Country>
        <Region>EU</Region>
      </Location>
      <Provider>Clan-Server</Provider>
    </Server>
    <Server Index="8" Hostname="TAL.DE.EU.GameSurge.net" Ports="6660,6666-6669">
      <Location>
        <City>Wuppertal</City>
        <Country>DE</Country>
        <Region>EU</Region>
      </Location>
      <Provider>TAL.DE</Provider>
    </Server>
    <Server Index="9" Hostname="TechConnect.NL.EU.GameSurge.net" Ports="6667-6669,7000">
      <Location>
        <City>Sittard</City>
        <Country>NL</Country>
        <Region>EU</Region>
      </Location>
      <Provider>TechConnect</Provider>
    </Server>
    <Server Index="10" Hostname="Snoke.NL.EU.GameSurge.net" Ports="6667-6669,7000">
      <Location>
        <City>Amsterdam</City>
        <Country>NL</Country>
        <Region>EU</Region>
      </Location>
      <Provider>Snoke</Provider>
    </Server>
  </Network>
  <Network Name="Undernet">
    <Server Index="0" Hostname="Dallas.TX.US.Undernet.org" Ports="6660-6669,7000">
      <Location>
        <City>Dallas</City>
        <State>TX</State>
        <Country>US</Country>
      </Location>
      <Provider>Globalcon.net LLC</Provider>
    </Server>
    <Server Index="1" Hostname="mesa.az.us.undernet.org" Ports="6660,6665-6667,7000">
      <Location>
        <City>Mesa</City>
        <State>AZ</State>
        <Country>US</Country>
      </Location>
      <Provider>Easy News</Provider>
    </Server>
  </Network>
  <Network Name="EFnet">
    <Server Index="0" Hostname="irc.paraphysics.net" Ports="6660-6669">
      <Location>
        <City>Houston</City>
        <State>TX</State>
        <Country>US</Country>
      </Location>
      <Provider>nLayer</Provider>
    </Server>
  </Network>
  <Network Name="Doolanshire">
    <Server Index="0" Hostname="irc.doolanshire.net" Ports="6667">
      <Location>
        <Country>US</Country>
      </Location>
      <Provider>Doolanshire</Provider>
    </Server>
  </Network>
</Servers>
